<?php

/**
 * AffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AffiliateTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object AffiliateTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('Affiliate');
	}

	public function countToBeActivated() {
		$q = $this->createQuery('a')
		     ->where('a.is_active = ?', 0);

		return $q->count();
	}

}