<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
	public function countActiveJobs()
	{
		return $this->getActiveJobsQuery()->count();
	}
	
	public function getActiveJobs($max = 0)
	{
		$q = $this->getActiveJobsQuery();
		if ($max > 0) {
			$q->limit($max);
		}
		
		return $q->execute();
	}
	
	public function getActiveJobsQuery()
	{
		$q = $this->getJobsQuery();
		return JobTable::getInstance()->addActiveJobsQuery($q);
	}
	
	private function getJobsQuery()
	{
		return Doctrine_Query::create()
		       ->from('Job j')
		       ->where('j.category_id = ?', $this->getId());
	}
}
