# apps/frontend/config/routing.yml
affiliate:
  class: sfDoctrineRouteCollection
  options:
    model: Affiliate
    actions: [new, create]
    object_actions: { wait: get }

category:
  url: /category/:slug.:sf_format
  class: sfDoctrineRoute
  param: { module: category, action: show, sf_format: html }
  options: { model: Category, type: object }
  requirements:
    sf_format: (?:html|atom)

job:
  class: sfDoctrineRouteCollection
  options:
    model: Job
    column: token
    object_actions: { publish: put, extend: put }
  requirements:
    token: \w+
 
job_show_user:
  url: /job/:company_slug/:location_slug/:id/:position_slug
  class: sfDoctrineRoute
  options:
    model: Job
    type: object
    method_for_query: retrieveActiveJob
  param: { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [get]

job_search:
  url:   /search
  param: { module: job, action: search }

# api
api_jobs:
  url: /api/:token/jobs.:sf_format
  class: sfDoctrineRoute
  param: { module: api, action: list }
  options: { model: Job, type: list, method: getForToken }
  requirements:
    sf_format: (?:xml|json|yaml)

# default rules
homepage:
  url: /
  param: { module: job, action: index }
 
default_index:
  url: /:module
  param: { action: index }
 
default:
  url: /:module/:action/*