generator:
  class: sfDoctrineGenerator
  param:
    model_class: Affiliate
    theme: admin
    non_verbose_templates: true
    with_show: false
    singular: ~
    plural: ~
    route_prefix: affiliate
    with_doctrine_route: true
    actions_base_class: sfActions
  
    config:
      fields:
        is_active:
          label: Active?
      list:
        title: Affiliate Management
        display:
          - is_active
          - url
          - email
          - token
        sort:
          - is_active
        object_actions:
          _edit: ~
          activate: ~
          deactivate: ~
        batch_actions:
          activate: ~
          deactivate: ~
        actions: {}
      filter:
        display:
          - url
          - email
          - is_active